version: '3.9'

services:
  database:
    image: 'postgres:14.4-alpine'
    ports:
      - '5432:5432'
    volumes:
      - compr:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  compr:
